authentication:
  allow_anonymous_access: true
  single_user_api_key: secret
trees:
  - tree: catalog
    path: /bmm/standards
    args:
      uri: catalog.db
      adapters_by_mimetype:
        text/x-xdi: xdi:read_xdi
      # Tiled will not serve anything that is outside the directory (directories)
      # listed here. It is a security feature to protect against something like
      # /etc/passwd getting registered and served.
      readable_storage:
        - /home/bruce/git/bmm-standards/Data     
      writable_storage: /home/bruce/git/bmm-standards/Processed
allow_origins:
  - https://vega.github.io
